### ISSUE TITLE
前端脑图在线查看网站

### ISSUE THREAD

**Issue by KonghaYao** [jCodeLife/mind-map#4]
您好，@jCodeLife：
       最近在掘金上看到了您对于这个仓库的分享，所以灵光一现制作了一个在线查看这个仓库文件的网站，以方便众多学习者查看。
       [前端脑图网站](https://front-end-mind-map.netlify.app/#/index) [网站代码仓库](https://github.com/KonghaYao/front-end-mind-map-display)
       感谢您对于知识的分享，让我们能够更加容易地学习与进步！
署名：@konghayao 江夏尧

**Comment by starEDU** [comment]
@KonghaYao 大佬是用什么库解析渲染 **.xmind**和 **.md** 文件在网页上的？

**Comment by KonghaYao** [comment]
.xmind 格式是 xmind 官方提供的一个插件直接可以渲染的 [xmind-embed-viewer](https://github.com/xmindltd/xmind-embed-viewer) 原理是 iframe 加 postMessage 方式进行数据沟通将主页面的 文件的 arrayBuffer 传给那个网站。
.md 是采用 [remake](https://www.npmjs.com/package/remark) 进行渲染的，markdown 转成 html，然后使用的是 [github 风格的 css 文件 ](https://www.npmjs.com/package/github-markdown-css)

**Comment by KonghaYao** [comment]
@starEDU 在源代码里面有更详细的使用 :smile: 
哦，markdown 那个库叫 remark，打错字了
